# -*- coding: utf-8 -*-
"""question2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROaZZFi22-Jo93s8wWVChZguwpiNpIVJ
"""

count = 0

def add():
    global count
    count += 1

print("Previous:", count)
add()
print("New:", count)

animals = ["tiger", "lion", "snake"]

def add_animal(animal_list):
    animal_list.append("elephant")

print("Previous:", animals)
add_animal(animals)
print("New:", animals)